---
- name: Install Nginx, PHP FPM
  hosts: webservers
  vars:
   debian_codename: jessie
   default_timezone: Europe/Kiev
   default_locale: ru_RU.UTF-8
   default_upload_max_filesize: 4
   default_php_user: user
   default_php_group: user
   default_php_memory_limit: 128
   default_mysql_root_password: access
   default_mysql_user_login: user
   default_mysql_user_password: access
  remote_user: user
  become: yes
  become_method: sudo
  #accelerate: true
  max_fail_percentage: 10
  serial:
   - "10%"
   - "20%"
   - "100%"
  roles:
   - common
   - nginx
#   - nginx-http2
   - php-fpm
   - gearman-server
   - gearman-client
   - postfix
   - mysql
   - nodejs
   - mongodb

