---
- name: Download setup_6.x
  get_url:
    url: https://deb.nodesource.com/setup_6.x
    dest: /tmp/setup_6.x.sh
    mode: 0777

- name: Run setup_6.x.sh
  shell: bash setup_6.x.sh
  args:
    chdir: /tmp/

- name: NodeJS | Updating apt cache
  apt:
    update_cache: yes

- name: NodeJS | Install packages
  apt: name={{item}}
  with_items:
    - libcairo2-dev
    - libjpeg-dev
    - libpango1.0-dev
    - libgif-dev
    - nodejs

- name: Clean cache
  command: npm cache clean -f

- name: Npm upgrade to latest version
  command: npm install npm@latest -g

- name: Install n package
  command: npm install -g n
