---
- name: GEARMAN SERVER | Install list of gearmand server nessesary packages
  apt: name={{item}}
  with_items:
    - gcc
    - g++
    - libboost-dev
    - libboost-program-options-dev
    - libboost-all-dev
    - libevent-dev
    - cloog-ppl
    - gperf
    - uuid-dev
    - libgearman-dev


- name: Get the Latest Gearman Job Server
  get_url: url=https://launchpad.net/gearmand/1.2/1.1.12/+download/gearmand-1.1.12.tar.gz dest=/opt/

- name: go to folder untar
  command: chdir=/opt tar -xvzf gearmand-1.1.12.tar.gz

- name: Configure
  command: chdir=/opt/gearmand-1.1.12 ./configure

- name: Make Gearman
  command: chdir=/opt/gearmand-1.1.12 make

- name: Make Install The Gearman
  command: chdir=/opt/gearmand-1.1.12 make install

- name: Make Install The Gearman
  command: chdir=/opt/gearmand-1.1.12 ldconfig

- template:
    src: ../templates/etc/init.d/gearmand.j2
    dest: /etc/init.d/gearmand
    owner: root
    group: root
    mode: "u=rwx,go=rx"
    backup: yes

- name: Update script list
  command: update-rc.d -f gearmand defaults

#- name: Reload systemctl daemon
#  command: systemctl daemon-reload

- name: Ensure my daemon myd is started
  action: service name=gearmand state=started
