---
- name: test connection
  ping:
  remote_user: user

- name: Run the equivalent of "apt-get update" as a separate step
  apt:
   update_cache: yes

- name: Update all packages to the latest version
  apt:
    upgrade: dist

- name: Install list of common packages
  apt: name={{item}}
  with_items:
    - vim
    - htop
    - cron
    - zip
    - unzip
    - wget
    - curl
    - mc
    - sudo
    - apache2-utils
    - debconf-utils
    - ipset
    - debian-keyring
    - fail2ban
    - git
    - lsb-release
    - bsdutils
    - build-essential
    - libaio1
    - libcurl4-openssl-dev
    - libevent-dev
    - module-init-tools


# Ensure a locale exists.
- locale_gen:
    name: ru_RU.UTF-8
    state: present

- name: update locales
  command: dpkg-reconfigure --frontend noninteractive locales

- name: set timezone to Europe/Kiev
  timezone:
    name: Europe/Kiev

- name: write vimrc
  copy: src=vimrc dest=/etc/vim/vimrc owner=root group=root mode=0644

- name: correct default editor
  alternatives:
    name: editor
    path: /usr/bin/vim.basic

- name: correct default editor
  alternatives:
    name: vim
    path: /usr/bin/vim.basic

- name: correct default editor
  alternatives:
    name: vimdiff
    path: /usr/bin/vim.basic

